// Bu dosya tools/excel_to_data.py ile Excel tablosundan üretilir; elle düzenleme yerine tabloyu güncelle.
window.LIBRARY_DATA = {
  "universities": [
    {
      "name": "KU Leuven (Group T)",
      "program": "Engineering Technology (B.Sc.)",
      "country": "Belçika",
      "city": "Leuven",
      "open": "9 Eki 2026",
      "close": null,
      "fee": null,
      "qs": "59",
      "the": "46",
      "todo": "OMPT-G ≥ %60 (online, gözetimli; 26 soru / 180 dk; matematik → kimya). Plan: Kasım–Aralık. YKS asgari puanı yok, SAT kabul edilmiyor (Group T maili).",
      "acceptance": null,
      "note": "Tarihler KU Leuven 'Application Window' aracında; Group T 2027 şart sayfası linki mailde.",
      "group": "ana",
      "short": "KU Leuven",
      "code": "be",
      "todoItems": [
        "OMPT-G ≥ %60 (online, gözetimli; 26 soru / 180 dk; matematik → kimya)",
        "Plan: Kasım–Aralık",
        "YKS asgari puanı yok, SAT kabul edilmiyor (Group T maili)"
      ],
      "id": 1
    },
    {
      "name": "DTU – Technical University of Denmark",
      "program": "General Engineering (B.Sc.)",
      "country": "Danimarka",
      "city": "Kongens Lyngby",
      "open": "1 Şub 2027",
      "close": "15 Mar 2027 (12:00 DK saati)",
      "fee": "€15.000",
      "qs": "105",
      "the": "121",
      "todo": "Ön değerlendirme – son gün 1 Kas 2026. Statement of Hours müdür imzalı (1 Eki, taranmış). Kalan: unistart.dtu.dk'ye yükleme + €100 ücret (İtalya'dan önce)",
      "acceptance": null,
      "note": "Asıl başvuru optagelse.dk. Ön değerlendirme 1 Eyl–1 Kas 2026 (unistart.dtu.dk). Ücret: dtu.dk (revize edilebilir).",
      "group": "ana",
      "short": "DTU",
      "code": "dk",
      "todoItems": [
        "Ön değerlendirme – son gün 1 Kas 2026",
        "Statement of Hours müdür imzalı (1 Eki, taranmış)",
        "Kalan: unistart.dtu.dk'ye yükleme + €100 ücret (İtalya'dan önce)"
      ],
      "id": 2
    },
    {
      "name": "Aalto University",
      "program": "Science and Technology: Data Science / Mechanical and Civil Engineering",
      "country": "Finlandiya",
      "city": "Espoo",
      "open": "7 Oca 2027",
      "close": "22 Oca 2027",
      "fee": "€12.000",
      "qs": "126 (eşit)",
      "the": "195 (eşit)",
      "todo": "Karar (6 Eki): SAT'a tekrar girilecek. Toplam ≥ 1350 gerekli (mevcut 1250). Skor 29 Oca 2027'ye kadar ulaşmalı; Aralık SAT kaydı Kasım başı kapanıyor.",
      "acceptance": null,
      "note": "aalto.fi (2026 dönemi bilgisi; Eylül'de güncelleneceği yazıyor).",
      "group": "ana",
      "short": "Aalto",
      "code": "fi",
      "todoItems": [
        "Karar (6 Eki): SAT'a tekrar girilecek",
        "Toplam ≥ 1350 gerekli (mevcut 1250)",
        "Skor 29 Oca 2027'ye kadar ulaşmalı",
        "Aralık SAT kaydı Kasım başı kapanıyor"
      ],
      "id": 3
    },
    {
      "name": "École Polytechnique",
      "program": "Bachelor of Science (Matematik & Ekonomi / Fizik / Bilgisayar)",
      "country": "Fransa",
      "city": "Palaiseau",
      "open": "17 Eyl 2026",
      "close": "20 Eki 2026 (1. tur; okul maili '11:59 Paris' yazıyor)",
      "fee": null,
      "qs": "43 (eşit) (IP Paris)",
      "the": "68 (eşit) (IP Paris)",
      "todo": "Referanslar portala girildi (1 Eki): Elif Şimşek (matematik) + Halit Murat Özen (AP Calculus) – mektuplar 13 Eki'ye kadar. Kalan: belgeler, CV, €105 ücret. Hedef gönderim: 15 Eki",
      "acceptance": null,
      "note": "2. tur: 21 Eki 2026–6 Oca 2027 · 3. tur: 7 Oca–8 Şub 2027. Kaynak: programmes.polytechnique.edu · Sıralamalarda Institut Polytechnique de Paris olarak geçiyor.",
      "group": "ana",
      "short": "Polytechnique",
      "code": "fr",
      "todoItems": [
        "Referanslar portala girildi (1 Eki): Elif Şimşek (matematik) + Halit Murat Özen (AP Calculus) – mektuplar 13 Eki'ye kadar",
        "Kalan: belgeler, CV, €105 ücret",
        "Hedef gönderim: 15 Eki"
      ],
      "id": 4
    },
    {
      "name": "UvA – University of Amsterdam",
      "program": "Econometrics and Data Science (B.Sc.)",
      "country": "Hollanda",
      "city": "Amsterdam",
      "open": "1 Eki 2026",
      "close": "1 Nis 2027",
      "fee": null,
      "qs": "60",
      "the": "62 (eşit)",
      "todo": "Birinci yılı tamamla; OMPT-D ≥ %70 istenebilir. Studielink 1 Eki (öğr. no 17122295). SIS'te başvuruyu tamamla + gönder: kişisel son tarih 16 Eki 2026 (UvA maili 2 Eki). Checklist: kabul, UvA Matching, okul ücreti",
      "acceptance": null,
      "note": "Hollanda ana liste #1 · QS: sayfa 60 gösteriyor, yılı açıkça yazmıyor.",
      "group": "ana",
      "short": "UvA",
      "code": "nl",
      "todoItems": [
        "Birinci yılı tamamla",
        "OMPT-D ≥ %70 istenebilir",
        "Studielink 1 Eki (öğr. no 17122295)",
        "SIS'te başvuruyu tamamla + gönder: kişisel son tarih 16 Eki 2026 (UvA maili 2 Eki)",
        "Checklist: kabul, UvA Matching, okul ücreti"
      ],
      "id": 5
    },
    {
      "name": "VU Amsterdam",
      "program": "Mathematics (B.Sc.)",
      "country": "Hollanda",
      "city": "Amsterdam",
      "open": "1 Eki 2026",
      "close": "1 Nis 2027",
      "fee": null,
      "qs": "185 (eşit)",
      "the": "176 (eşit)",
      "todo": "Birinci yılı tamamla (en az 1 yıllık kredi). Studielink 1 Eki (öğr. no 2944462); VU panelinde başvuruyu 6 hafta içinde (~12 Kas) %100 yap; giriş bilgileri geldi (2 Eki). Kabulden sonra onaylı diploma kopyası posta ile (en geç 31 Ağu 2027)",
      "acceptance": null,
      "note": "Hollanda ana liste #2",
      "group": "ana",
      "short": "VU Amsterdam",
      "code": "nl",
      "todoItems": [
        "Birinci yılı tamamla (en az 1 yıllık kredi)",
        "Studielink 1 Eki (öğr. no 2944462)",
        "VU panelinde başvuruyu 6 hafta içinde (~12 Kas) %100 yap",
        "Giriş bilgileri geldi (2 Eki)",
        "Kabulden sonra onaylı diploma kopyası posta ile (en geç 31 Ağu 2027)"
      ],
      "id": 6
    },
    {
      "name": "TU Eindhoven (TU/e)",
      "program": "Industrial Engineering (B.Sc.)",
      "country": "Hollanda",
      "city": "Eindhoven",
      "open": "1 Eki 2026",
      "close": "1 May 2027 (23:59 CET)",
      "fee": null,
      "qs": "152",
      "the": "192 (eşit)",
      "todo": "Birinci yılı tamamla (60 AKTS), ortalama ≥ 3.0/4.0. OSIRIS belge adımına kadar dolduruldu. Kalan: İÜ belgeleri, CV, €100 başvuru ücreti; pasaport 31 Ara 2027'ye kadar geçerli olmalı",
      "acceptance": null,
      "note": "Hollanda ana liste #4. Son tarih TU/e mailinden (1 Eki). Göçmenlik belgeleri/ödeme: 1 Haz 2027.",
      "group": "ana",
      "short": "TU/e",
      "code": "nl",
      "todoItems": [
        "Birinci yılı tamamla (60 AKTS), ortalama ≥ 3.0/4.0. OSIRIS belge adımına kadar dolduruldu",
        "Kalan: İÜ belgeleri, CV, €100 başvuru ücreti",
        "Pasaport 31 Ara 2027'ye kadar geçerli olmalı"
      ],
      "id": 7
    },
    {
      "name": "University of Twente",
      "program": "Industrial Engineering and Management (B.Sc.)",
      "country": "Hollanda",
      "city": "Enschede",
      "open": "1 Eki 2026",
      "close": null,
      "fee": null,
      "qs": "223 (eşit)",
      "the": "190 (eşit)",
      "todo": "Uygunluk resmi başvuruda belli olacak. Studielink 1 Eki (öğr. no 3999971); OSIRIS anketi + €100 başvuru ücreti; İÜ belgeleri",
      "acceptance": null,
      "note": "Hollanda ana liste #3. 2027 şartları Ekim'de kontrol edilecek.",
      "group": "ana",
      "short": "Twente",
      "code": "nl",
      "todoItems": [
        "Uygunluk resmi başvuruda belli olacak",
        "Studielink 1 Eki (öğr. no 3999971)",
        "OSIRIS anketi + €100 başvuru ücreti",
        "İÜ belgeleri"
      ],
      "id": 8
    },
    {
      "name": "Universitat Pompeu Fabra (UPF)",
      "program": "Mathematical Engineering in Data Science",
      "country": "İspanya",
      "city": "Barselona",
      "open": null,
      "close": null,
      "fee": null,
      "qs": "263",
      "the": "187 (eşit)",
      "todo": "Diploma denkliği (başvuruda kesinleşmiş olmalı; sadece volante ile yerleştirmede son sıra). PCE Matematik + Fizik (katsayı 0,2) fiilen şart: PCE'siz en fazla 10 puan",
      "acceptance": null,
      "note": "Taban puan 2025-26: 11,818 (UPF notes de tall). Katalonya ön kaydı (Generalitat). PCE kararı Nisan sonu.",
      "group": "ana",
      "short": "UPF",
      "code": "es",
      "todoItems": [
        "Diploma denkliği (başvuruda kesinleşmiş olmalı; sadece volante ile yerleştirmede son sıra)",
        "PCE Matematik + Fizik (katsayı 0,2) fiilen şart: PCE'siz en fazla 10 puan"
      ],
      "id": 9
    },
    {
      "name": "Universidad Carlos III de Madrid (UC3M)",
      "program": "Aerospace Engineering (1. tercih)",
      "country": "İspanya",
      "city": "Madrid (Leganés)",
      "open": "5 Eki 2026 (Early Admission)",
      "close": null,
      "fee": null,
      "qs": "314 (eşit)",
      "the": "801–1000",
      "todo": "Tamamen İngilizce, 4 yıl / 240 ECTS, 100 kontenjan. Early Admission'da Data Science ile aynı başvuru (€150, en fazla 2 bölüm). Eksik: motivation letter (zorunlu) + €150 ödeme",
      "acceptance": null,
      "note": "Taban puan 2026/27 (1. tur, 14 üzerinden): 13,322. Kaynak: uc3m.es/bachelor-degree/aeroespace + cut-off grades.",
      "group": "ana",
      "short": "UC3M",
      "code": "es",
      "todoItems": [
        "Tamamen İngilizce, 4 yıl / 240 ECTS, 100 kontenjan",
        "Early Admission'da Data Science ile aynı başvuru (€150, en fazla 2 bölüm)",
        "Eksik: motivation letter (zorunlu) + €150 ödeme"
      ],
      "id": 10
    },
    {
      "name": "Universidad Carlos III de Madrid (UC3M)",
      "program": "Data Science and Engineering (2. tercih)",
      "country": "İspanya",
      "city": "Madrid (Leganés/Getafe)",
      "open": "5 Eki 2026 (Early Admission)",
      "close": null,
      "fee": null,
      "qs": "314 (eşit)",
      "the": "801–1000",
      "todo": "Early Admission: PCE/UNEDasiss yok, lise diplomasına göre değerlendirme. Yüklenecek: diploma PDF (hazır), transkript, YKS + tercüme (hazır), IELTS, pasaport, motivation letter (eksik); SAT/AP ek başarı. Apostil gerekmez. Şartlı kabul: kayıttan önce denklik volantesi, denklik 1. yıl içinde",
      "acceptance": null,
      "note": "Taban puan 2026/27 (1. tur): 11,677. UC3M kabul ofisi maili (1 Eki 2026). Başvuru ücreti €150 (2 bölüme kadar); motivation letter zorunlu; dosya ≤4 MB. Hedef gönderim 7 Eki.",
      "group": "ana",
      "short": "UC3M",
      "code": "es",
      "todoItems": [
        "Early Admission: PCE/UNEDasiss yok, lise diplomasına göre değerlendirme",
        "Yüklenecek: diploma PDF (hazır), transkript, YKS + tercüme (hazır), IELTS, pasaport, motivation letter (eksik)",
        "SAT/AP ek başarı",
        "Apostil gerekmez",
        "Şartlı kabul: kayıttan önce denklik volantesi, denklik 1. yıl içinde"
      ],
      "id": 11
    },
    {
      "name": "Lund University",
      "program": "Sciences – Mathematics (B.Sc.)",
      "country": "İsveç",
      "city": "Lund",
      "open": "Ekim ortası 2026",
      "close": "15 Oca 2027",
      "fee": null,
      "qs": "71",
      "the": "95 (eşit)",
      "todo": "Türk lise matematiğinin 'Matematik 4' denkliği (belge üzerinden değerlendiriliyor)",
      "acceptance": null,
      "note": "universityadmissions.se; belgeler 1 Şub 2027'ye kadar. Kaynak: lunduniversity.lu.se",
      "group": "ana",
      "short": "Lund",
      "code": "se",
      "todoItems": [
        "Türk lise matematiğinin 'Matematik 4' denkliği (belge üzerinden değerlendiriliyor)"
      ],
      "id": 12
    },
    {
      "name": "Charles University (FSV)",
      "program": "Economics and Finance – BEF (B.A.)",
      "country": "Çekya",
      "city": "Prag",
      "open": "1 Kas 2026",
      "close": null,
      "fee": null,
      "qs": "273 (eşit)",
      "the": "401–500",
      "todo": "Yok (AP Calculus AB 5 matematik şartını karşılıyor)",
      "acceptance": null,
      "note": "Açılış: fsv.cuni.cz",
      "group": "yedek",
      "short": "Charles",
      "code": "cz",
      "todoItems": [
        "Yok (AP Calculus AB 5 matematik şartını karşılıyor)"
      ],
      "id": 13
    },
    {
      "name": "CTU – Czech Technical University",
      "program": "Mechanical Engineering (B.Sc.)",
      "country": "Çekya",
      "city": "Prag",
      "open": null,
      "close": null,
      "fee": null,
      "qs": "432 (eşit)",
      "the": "1201–1500",
      "todo": "Diploma denkliği (Prag Belediyesi; fark çıkarsa denklik sınavı); matematik giriş sınavı",
      "acceptance": null,
      "note": null,
      "group": "yedek",
      "short": "ČVUT · CTU",
      "code": "cz",
      "todoItems": [
        "Diploma denkliği (Prag Belediyesi; fark çıkarsa denklik sınavı)",
        "Matematik giriş sınavı"
      ],
      "id": 14
    },
    {
      "name": "VU Amsterdam",
      "program": "Econometrics and Operations Research (B.Sc.)",
      "country": "Hollanda",
      "city": "Amsterdam",
      "open": "1 Eki 2026",
      "close": "1 Nis 2027",
      "fee": null,
      "qs": "185 (eşit)",
      "the": "176 (eşit)",
      "todo": "Birinci yılı tamamla (en az 1 yıllık kredi)",
      "acceptance": null,
      "note": "Yedek (29 Eyl: ana listeden çıktı, yerine Twente IEM)",
      "group": "yedek",
      "short": "VU Amsterdam",
      "code": "nl",
      "todoItems": [
        "Birinci yılı tamamla (en az 1 yıllık kredi)"
      ],
      "id": 15
    },
    {
      "name": "University of Groningen",
      "program": "Applied Mathematics (B.Sc.)",
      "country": "Hollanda",
      "city": "Groningen",
      "open": null,
      "close": null,
      "fee": null,
      "qs": "157",
      "the": "82",
      "todo": "4. AP (sonuç 1 May'dan sonra geliyor; koşullu kabul sorulmadı)",
      "acceptance": null,
      "note": "Yedek. Mathematics sayfasında 1 Eki 2026–1 May 2027 ve €19.800 yazıyor; bu program için ayrıca doğrulanmadı.",
      "group": "yedek",
      "short": "Groningen",
      "code": "nl",
      "todoItems": [
        "4. AP (sonuç 1 May'dan sonra geliyor; koşullu kabul sorulmadı)"
      ],
      "id": 16
    },
    {
      "name": "University of Groningen",
      "program": "Industrial Engineering and Management (B.Sc.)",
      "country": "Hollanda",
      "city": "Groningen",
      "open": null,
      "close": null,
      "fee": null,
      "qs": "157",
      "the": "82",
      "todo": "4. AP (sonuç 1 May'dan sonra geliyor)",
      "acceptance": null,
      "note": "Yedek",
      "group": "yedek",
      "short": "Groningen",
      "code": "nl",
      "todoItems": [
        "4. AP (sonuç 1 May'dan sonra geliyor)"
      ],
      "id": 17
    },
    {
      "name": "TU Eindhoven (TU/e)",
      "program": "Applied Mathematics (B.Sc.)",
      "country": "Hollanda",
      "city": "Eindhoven",
      "open": null,
      "close": null,
      "fee": null,
      "qs": "152",
      "the": "192 (eşit)",
      "todo": "Birinci yılı tamamla (60 AKTS), ortalama ≥ 3.0/4.0",
      "acceptance": null,
      "note": "Yedek",
      "group": "yedek",
      "short": "TU/e",
      "code": "nl",
      "todoItems": [
        "Birinci yılı tamamla (60 AKTS), ortalama ≥ 3.0/4.0"
      ],
      "id": 18
    },
    {
      "name": "University of Twente",
      "program": "Applied Mathematics (B.Sc.)",
      "country": "Hollanda",
      "city": "Enschede",
      "open": "Ekim 2026",
      "close": null,
      "fee": null,
      "qs": "223 (eşit)",
      "the": "190 (eşit)",
      "todo": "Uygunluk resmi başvuruda belli olacak",
      "acceptance": null,
      "note": "Yedek. utwente.nl: 'Ekim'den itibaren' – kesin gün yok.",
      "group": "yedek",
      "short": "Twente",
      "code": "nl",
      "todoItems": [
        "Uygunluk resmi başvuruda belli olacak"
      ],
      "id": 19
    },
    {
      "name": "Tilburg University",
      "program": "Econometrics and Operations Research (B.Sc.)",
      "country": "Hollanda",
      "city": "Tilburg",
      "open": null,
      "close": null,
      "fee": "€13.400 (2026-27)",
      "qs": "429",
      "the": "301–350",
      "todo": "VWO seviyesinde matematik kanıtı (yöntemi belirsiz)",
      "acceptance": null,
      "note": "Yedek. Ücret: tilburguniversity.edu",
      "group": "yedek",
      "short": "Tilburg",
      "code": "nl",
      "todoItems": [
        "VWO seviyesinde matematik kanıtı (yöntemi belirsiz)"
      ],
      "id": 20
    }
  ],
  "notes": [
    "Sarı hücreler: boş bırakıldı, senin doldurman için. Sadece üniversitelerin kendi sitelerinden doğrulanan bilgiler yazıldı.",
    "QS 2027 ve THE 2026 (en güncel) sıraları topuniversities.com ve timeshighereducation.com üniversite sayfalarından. '(eşit)' = başka üniversiteyle aynı sırayı paylaşıyor. Tahmini kabul oranı boş.",
    "Ücretler 2026-27 yılına ait; 2027-28'de artabilir.",
    "Son güncelleme: 6 Ekim 2026 (liste 10 üniversiteye indirildi; Bologna, TUM, UPF+UPC çıkarıldı)"
  ]
};
